services:
  db:
    image: postgres
    restart: always
    # Set shared memory limit
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file: .env

volumes:
  pgdata:
